### ISSUE TITLE
management-team3-question7-feedback

### ISSUE THREAD

**Issue by Jordan-A** [Allegheny-Computer-Science-203-S2020/cs203-S2020-management#2]
We just added our initial response to question seven of the management repository. It would be helpful to get feedback from you so that we can improve our work.

The update can be found at the following commit: https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/commit/f5e5fcb82b56b48d9f8ea6ef91cd82908faa44cc

**Comment by lussierc** [comment]
I really appreciate the language:
>  We will take on blame-less postmortems as problem that is a collective
   responsibility to solve.

I really like the wording "collective responsibility" as I feel this encompasses the "blameless" part of blameless postmortems.

I would work to improve some of the grammar a little bit, such as instead of saying, "a GitHub issue tracker", I would say, "the GitHub issue tracker" since it is an entire tool.

Overall, I think it looks very good so far!

**Comment by Jordan-A** [comment]
I just implemented your suggested changes in the following commit. https://github.com/Allegheny-Computer-Science-203-S2020/cs203-S2020-management/commit/7d45b9c33ba16f9c89810a5ed85e3716dfd3f7e6

**Comment by santacruzm** [comment]
I agree with the suggestions and changes presented as the GitHub Issue Tracker ultimately is a vital tool.

**Comment by enpuyou** [comment]
@Jordan-A Thanks for raising issues here. I would suggest that you move this into the PR in the future since it will be easier for everyone to see the progress and content and trace the update in a PR's setting. You can also add a `WIP:` before the PR title to note that the PR is still "work in progress"

**Comment by Jordan-A** [comment]
I agree with the idea of a pull request. @santacruzm is creating one at the moment.
